if &compatible
  set nocompatible
endif

" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  " Enable multiple cursor selection
  call dein#add('terryma/vim-multiple-cursors')

  " Add shortcuts to comment code
  call dein#add('preservim/nerdcommenter')

  " Add shortcuts to manage surrounding tags
  call dein#add('tpope/vim-surround')

  " Fuzzy file finder
  call dein#add('ctrlpvim/ctrlp.vim')

  " Improve the status bar with git info and more
  call dein#add('vim-airline/vim-airline')

  " Compatibility with editorconfig
  call dein#add('editorconfig/editorconfig-vim')

  " Show git
  call dein#add('airblade/vim-gitgutter')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

"if dein#check_install()
"  call dein#install()
"endif

" Disable automatic visual mode using mouse
set mouse-=a

" Leader key
let mapleader = ","
let g:mapleader = ","

" UTF-8 encoding
set encoding=utf-8

" Auto read when file is changed from outside
set autoread

" Line numbers
set number

" Easy indent
vnoremap < <gv
vnoremap > >gv
nnoremap < <<
nnoremap > >>

" French help if available
set helplang=fr

" Ignore case
set ignorecase

" Ignore case only when lowercase letters
set smartcase

" Search immediately
set incsearch

" Round indent to multiple of shiftwidth
set shiftround

" Ignore ignored files for ctrlp
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" Let 5 lines above and below cursor
set scrolloff=5

" New tab with leader + t
noremap <silent> a :tabnew<cr>

" Close tab with leader + q
noremap <silent> q :tabclose<cr>


" 0 threshold for reporting the number of lines changed with : commands
set report=0

" Fast terminal connection => smoother rendering
set ttyfast
