if &compatible
  set nocompatible
endif

" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  " Enable multiple cursor selection
  call dein#add('terryma/vim-multiple-cursors')

  " Add shortcuts to comment code
  call dein#add('preservim/nerdcommenter')

  " Add shortcuts to manage surrounding tags
  call dein#add('tpope/vim-surround')

  " Fuzzy file finder
  call dein#add('ctrlpvim/ctrlp.vim')

  " Improve the status bar with git info and more
  call dein#add('vim-airline/vim-airline')

  " Compatibility with editorconfig
  call dein#add('editorconfig/editorconfig-vim')

  " Show git
  call dein#add('airblade/vim-gitgutter')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

"if dein#check_install()
"  call dein#install()
"endif

" Disable automatic visual mode using mouse
"set mouse-=a
