# ~/.bashrc: executed by bash(1) for non-login shells.

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

if [[ -n "$(ls -A $HOME/.systemrc 2>/dev/null)" ]]; then
  for script in "$HOME"/.systemrc/*.sh; do
    source $script
  done
fi
